name: Build

on:
  push:
    branches: ["main"]
    tags:
      - "*"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.3"

      - name: Install dependencies
        run: go get .

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o webhookserver_linux_amd64
          GOOS=linux GOARCH=arm64 go build -o webhookserver_linux_arm64
          GOOS=darwin GOARCH=amd64 go build -o webhookserver_darwin_amd64
          GOOS=darwin GOARCH=arm64 go build -o webhookserver_darwin_arm64

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            webhookserver_linux_amd64
            webhookserver_linux_arm64
            webhookserver_darwin_amd64
            webhookserver_darwin_arm64
